services:
  prima:
    build:
      context: ../
      dockerfile: ./cicd/Dockerfile
    container_name: prima
    env_file: ../.env #env.local on gitignore,
    command: "symfony server:start --no-tls"
    volumes:
      - ../:/app/
    ports:
      - "8000:8000"