services:
  collective-minds-subjects:
    build:
      context: ../
      dockerfile: ./cicd/Dockerfile
    container_name: collective-minds-subjects
    env_file: ../.env
    command: "symfony server:start --no-tls"
    volumes:
      - ../:/app/
    ports:
      - "8000:8000"

  mock:
    image: jordimartin/mmock
    container_name: collective-minds-core-service-mock
    ports:
      - "8082:8082"
      - "8083:8083"
    volumes:
      - ./mock:/config
