# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    core_service.base_url: '%env(CORE_SERVICE_BASE_URL)%'

services:
    _defaults:
        autowire: false
        autoconfigure: false

    #I am not really a fan of autowire. We can add some general bindings and so on here
    # to use specific implementations, and then group configuration for a shorter file
    # but I'd rather explicitly explain what I am using.
    # even though it might mean more writing.

    # Use the fully qualified name for easier config on: routing, on whether adding command bus etc.

    Cesc\CMRad\Application\Subject\CreateSubjectCommandHandler:
        class: Cesc\CMRad\Application\Subject\CreateSubjectCommandHandler
        arguments:
            - '@api_repository.subjects'

    Cesc\CMRad\Application\Project\EnrollSubjectCommandHandler:
        class: Cesc\CMRad\Application\Project\EnrollSubjectCommandHandler
        arguments:
            - '@api_repository.projects'
            - '@api_repository.subjects'

    api_repository.projects:
        class: Cesc\CMRad\Infrastructure\ApiClient\ProjectRepositoryCoreApiClient
        arguments:
            - '@guzzlehttp.client'
            - '%core_service.base_url%'

    api_repository.subjects:
        class: Cesc\CMRad\Infrastructure\ApiClient\SubjectRepositoryCoreApiClient
        arguments:
            - '@guzzlehttp.client'
            - '%core_service.base_url%'

    # APi Clients
    guzzlehttp.client:
        class: GuzzleHttp\Client
        lazy: true

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class

    Cesc\CMRad\Infrastructure\Controller\Subject\CreateSubjectController:
        class: Cesc\CMRad\Infrastructure\Controller\Subject\CreateSubjectController
        arguments:
            - '@Cesc\CMRad\Application\Subject\CreateSubjectCommandHandler'
        tags: [ 'controller.service_arguments' ]


    Cesc\CMRad\Infrastructure\Controller\Project\EnrollSubjectController:
        class: Cesc\CMRad\Infrastructure\Controller\Project\EnrollSubjectController
        tags: [ 'controller.service_arguments' ]
        arguments:
            - '@Cesc\CMRad\Application\Project\EnrollSubjectCommandHandler'